<?php

/**
 * @file
 * Cavalla_tm module file.
 */

use Drupal\cavalla\Entity\Cavalla;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\media\Entity\Media;
use Drupal\cavalla_tm\Entity\CavallaTm;
use Drupal\paragraphs\Entity\Paragraph;




/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_tm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_tm':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme(). Lets us define our paragraphs templates in this module.
 */
function cavalla_tm_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__cavalla_tm' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph templates.
 */
function cavalla_tm_preprocess_paragraph__cavalla_tm(&$variables) {

  $paragraph = $variables['elements']['#paragraph'];
  $variables['#attached']['library'][] = 'cavalla/text-media-js';

  $site_block = $paragraph->field_cavalla_copy__site_blocks->getValue();
  $variables['site_blocks'] = CavallaTm::getInstance()->getValue($site_block);
}



      
      
    