<?php

/**
 * @file
 * cavalla_search module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\cavalla\Entity\Cavalla;



/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_search':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function cavalla_search_theme($existing, $type, $theme, $path) {
  return [
    'node__cavalla_search' => [
      'base hook' => 'node',
    ],

  ];
}

function cavalla_search_preprocess_node__cavalla_search(array &$variables) {
  $node = $variables['elements']['#node'];
  $variables['page_title']=$node->getTitle();
  $variables['image'] = Cavalla::getInstance()->getMediaUrl($node->get('field_cavalla_search__hero')->getValue()); 
}