<?php

/**
 * @file
 * cavalla_tab module file.
 */

use Drupal\cavalla_tab\Entity\CavallaTab;
use Drupal\cavalla\Entity\Cavalla;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\media\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;



/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_tab_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_tab':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme(). Lets us define our paragraphs templates in this module.
 */
function cavalla_tab_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__cavalla_tab' => [
      'base hook' => 'paragraph',
    ],
    'tabs' => [
      'base hook' => 'paragraph',
    ],
    'mobile-tabs' => [
      'base hook' => 'paragraph',
    ],

  ];
}

/**
 * Implements hook_preprocess_HOOK() for cavalla_tab paragraph type.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements in the paragraph.
 */
function cavalla_tab_preprocess_paragraph__cavalla_tab(&$variables) {
  // Get the paragraph entity from the elements array.
  $tab = $variables['elements']['#paragraph'];
  $entity = $tab->field_cavalla_tabs__content->getValue() ?? [];
  $variables['tabs'] = CavallaTab::getInstance()->getValue($entity);

}



